M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu23.04.1} date Tue Aug 15 02:17:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-15T02:17:24+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X53.63Y-6.46
X59.41Y-6.46
T2
X29.22Y-8.08
X39.38Y-8.08
T0
M30
