M48
; DRILL file {KiCad 7.0.5.1-1-g8f565ef7f0-dirty-deb11} date Sun Jun 25 19:17:02 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-25T19:17:02+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5.1-1-g8f565ef7f0-dirty-deb11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X29.26Y-7.929
X39.42Y-7.929
T0
M30
