name: Build firmware

on:
  push:
    paths:
    - 'fw/**'
    - '**.yml'
  workflow_dispatch:
  workflow_call:
    inputs:
      build_type:
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          continue-on-error: true
          with:
            submodules: True

        - name: Install dependencies and build
          run: |
            export ARDUINO_LIBRARY_ENABLE_UNSAFE_INSTALL=true
            sudo snap install arduino-cli tree yq
            sudo apt-get install git tree python3

            ADIR=`arduino-cli config dump | yq eval .directories.data`
            
            arduino-cli core update-index --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json > /dev/null
            arduino-cli core install rp2040:rp2040 --additional-urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json > /dev/null

            arduino-cli lib install 'Adafruit TinyUSB Library@2.2.1' 'TMCStepper' 'Adafruit GFX Library' 'Adafruit BusIO' 'Adafruit SH110X' 'RP2040_PWM' 'microDS18B20'

            
            #sudo tree /home/runner/snap 
            sudo rm -r ${ADIR}/packages/rp2040/hardware/*
            # mkdir -p ${ADIR}/packages/rp2040
            git clone https://github.com/roman-dvorak/arduino-pico.git -b add_amfoc01 /home/runner/arduino-pico
            cd /home/runner/arduino-pico
            git submodule update --init
            cd pico-sdk
            git submodule update --init
            cd ../tools
            python3 ./get.py

            sudo ln -s /home/runner/arduino-pico ${ADIR}/packages/rp2040/hardware/rp2040

            cd ${{ github.workspace }}
            
            # Vypis konfigurace a podporovanych desek
            # arduino-cli config dump
            # arduino-cli board listall
            
            PLATFORM=rp2040:rp2040
            arduino-cli compile --verbose --warnings all --fqbn rp2040:rp2040:astrometers_amfoc01:flash=2097152_524288,usbstack=tinyusb --build-path fw  fw/amfoc01

            
        - name: Prepare data for build
          run: |
            mkdir -p fw/build || true
            mv fw/amfoc01.ino.uf2 fw/build/amfoc01.uf2
            echo "python3 upload.py --serial "/dev/ttyACM0" --family RP2040 --deploy amfoc01.uf2" > fw/build/upload.sh
            chmod +x fw/build/upload.sh
            git pull
        
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Bulid firmware"
            file_pattern: 'fw/build'
